spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: v1
#          uri: http://localhost:8083
          uri: lb://ribbon-consumer
          predicates:
            - Path=/test/*
        - id: v2
#          uri: http://localhost:8084
          uri: lb://register-customer
          predicates:
            - Path=/hello/*
server:
  port: 8088

eureka:
    client:
      service-url:
        defaultZone: http://peer1:1001/eureka/